using System.Collections.Generic;

namespace PvZWSTools_Shared.Helpers;

/// <summary>English 译文表。键就是界面里的中文原文，所以本文件只放"翻成什么"，
/// 不改变任何调用点：中文模式下这里一条都不会被读到。
///
/// 有意留白的两类：出怪类型那 40 个绰号（普僵/白眼/天尸…是社区叫法，等定译再补）、
/// 以及经典界面（ClassicMainWindow 与 oldui 基准逐字节对齐，动它就破 UI核对 第 4 项）。
/// <c>UI核对/check_i18n.py</c> 会钉住：这里的键必须在源码里真实存在，且 {0} 占位符两侧一致。</summary>
public static partial class Loc
{
    private static readonly Dictionary<string, string> EnTable = new()
    {
        // ---------- 导航（标题同时是查页用的键，只在显示这一层翻译） ----------
        ["杂项"] = "Misc",
        ["关卡"] = "Level",
        ["资源"] = "Resources",
        ["植物"] = "Plants",
        ["僵尸"] = "Zombies",
        ["出怪"] = "Spawning",
        ["战场"] = "Board",
        ["挑战"] = "Challenge",
        ["阵型"] = "Formation",
        ["娱乐"] = "Fun",
        ["快捷脚本"] = "Scripts",
        ["花园"] = "Garden",
        ["收藏"] = "Favorites",
        ["控制台"] = "Console",

        // ---------- 状态词：显示文案，不是协议值（协议走 "0"/"1"/"2"） ----------
        ["开启"] = "On",
        ["关闭"] = "Off",
        ["默认"] = "Default",
        ["未知"] = "Unknown",
        ["开"] = "On",
        ["关"] = "Off",
        ["已选 {0}/{1}"] = "Selected {0}/{1}",

        // ---------- 功能行的通用件 ----------
        ["搜索功能…"] = "Search functions…",
        ["按名称搜索全部功能"] = "Search all functions by name",
        ["状态管理"] = "State manager",
        ["环境"] = "Environment",
        ["获取更新"] = "Check for updates",
        ["打开文件目录"] = "Open data folder",
        ["缩小界面"] = "Zoom out",
        ["放大界面"] = "Zoom in",
        ["点击切换：全部 / 只看日志 / 只看收发"] = "Click to switch: All / Log only / Traffic only",
        ["自动滚动"] = "Auto scroll",
        ["暂停"] = "Pause",
        ["清空"] = "Clear",
        ["发送"] = "Send",
        ["攒住当前画面不再刷新；行照样收着，取消暂停就能看到"] =
            "Freeze the view; lines are still collected and appear when you resume.",
        ["写 Python/IronPython 语句直接发给游戏；Ctrl+Enter 发送"] =
            "Send Python/IronPython statements straight to the game; Ctrl+Enter to send.",
        ["全部"] = "All",
        ["只看日志"] = "Log only",
        ["只看收发"] = "Traffic only",
        ["取消连接提醒"] = "Suppress connect notices",
        // ---------- 清单：字段与通用件 ----------
        ["行"] = "Row",
        ["列"] = "Column",
        ["偏移X"] = "Offset X",
        ["偏移Y"] = "Offset Y",
        ["名称"] = "Name",
        ["模式"] = "Mode",
        ["关卡号"] = "Level No.",
        ["倍率"] = "Multiplier",
        ["下限"] = "Min",
        ["上限"] = "Max",
        ["槽位"] = "Slot",
        ["物品"] = "Item",
        ["道具"] = "Gadget",
        ["状态"] = "State",
        ["类型"] = "Type",
        ["阵型名"] = "Formation name",
        ["路状"] = "Road type",
        ["罐子类型"] = "Vase type",
        ["罐内植物"] = "Plant inside",
        ["罐内僵尸"] = "Zombie inside",
        ["限制"] = "Limit",
        ["沉睡"] = "Sleep",
        ["魅惑"] = "Charm",
        ["模仿者"] = "Imitater",
        ["{0}：点击在 关闭 / 开启 / 默认 之间循环"] = "{0}: tap to cycle Off / On / Default",
        ["{0}：点击换下一个取值"] = "{0}: tap for the next value",

        // ---------- 清单：杂项 ----------
        ["更新按钮状态"] = "Refresh button states",
        ["设置树的高度"] = "Set tree height",
        ["游戏速度"] = "Game speed",
        ["清除迷雾"] = "Clear fog",
        ["罐子透视"] = "See through vases",
        ["阳光增值"] = "Sun value boost",
        ["自动收集"] = "Auto collect",
        ["取消冷却"] = "No cooldown",
        ["自动浇水"] = "Auto water",
        ["取消阳光"] = "No sun cost",
        ["后台运行"] = "Run in background",
        ["去除遮挡"] = "Remove occlusion",
        ["补充肥料杀虫剂"] = "Refill fertilizer & pesticide",

        // ---------- 清单：关卡 ----------
        ["混乱关卡"] = "Shuffle level",
        ["设置无尽旗数"] = "Set endless flags",
        ["进入关卡"] = "Enter level",
        ["直接过关"] = "Clear level",

        // ---------- 清单：资源 ----------
        ["设置阳光"] = "Set sun",
        ["设置阳光上限"] = "Set sun cap",
        ["设置金钱"] = "Set coins",
        ["设置金钱上限"] = "Set coin cap",
        ["设置价值"] = "Set value",
        ["设置伤害"] = "Set damage",
        ["设置血量"] = "Set health",
        ["设置时间"] = "Set time",

        // ---------- 清单：植物 ----------
        ["植物无敌"] = "Plants invincible",
        ["只投黄油"] = "Butter only",
        ["植物清醒"] = "Plants awake",
        ["核弹无坑"] = "No blast crater",
        ["植物血量显示"] = "Show plant health",
        ["取消压扁"] = "No squash",
        ["准备时间显示"] = "Show recharge time",
        ["路灯花觉醒"] = "Plan-lamp awakened",
        ["伞弹车常驻"] = "Umbrella launcher always on",
        ["土豆准备时间"] = "Potato recharge",
        ["大嘴准备时间"] = "Chomper recharge",
        ["光菇准备时间"] = "Light-shroom recharge",
        ["磁菇准备时间"] = "Magnet-shroom recharge",
        ["炮准备时间"] = "Cannon recharge",
        ["超嘴准备时间"] = "Super chomper recharge",
        ["龙舌兰大招"] = "Agave ultimate",
        ["火红莲大招"] = "Fire lotus ultimate",
        ["其他准备时间"] = "Other recharge",

        // ---------- 清单：僵尸 ----------
        ["僵尸无敌"] = "Zombies invincible",
        ["停滞不前"] = "No advance",
        ["冰车无痕"] = "No Zamboni tracks",
        ["丑椒不爆"] = "Ugly pepper won't blow",
        ["僵尸血量显示"] = "Show zombie health",
        ["僵尸掉落卡片"] = "Zombies drop cards",
        ["小偷不偷"] = "Thief won't steal",
        ["魅惑有效"] = "Mind control works",
        ["取消限制"] = "Remove limits",
        ["施加僵尸状态"] = "Apply zombie status",

        // ---------- 清单：战场 ----------
        ["放置植物"] = "Place plant",
        ["放置僵尸"] = "Place zombie",
        ["放置物品"] = "Place item",
        ["放置道具"] = "Place gadget",
        ["列放置"] = "Place by column",
        ["清除所有"] = "Clear all",
        ["触发"] = "Trigger",
        ["恢复"] = "Restore",
        ["删除"] = "Delete",
        ["一键搭梯"] = "Auto ladder",
        ["限定植物"] = "Limited plants",
        ["自由种植"] = "Free planting",
        ["立即存档"] = "Save now",
        ["立即回档"] = "Load now",
        ["禁止存档"] = "Disable saving",
        ["储存植物"] = "Store plants",
        ["储存梯子"] = "Store ladders",
        ["储存罐子"] = "Store vases",
        ["同步格子"] = "Sync grid",
        ["格子类型"] = "Grid type",
        ["设置路状"] = "Set road type",

        // ---------- 清单：挑战 ----------
        ["风暴"] = "Storm",
        ["传送带"] = "Conveyor",
        ["砸罐子"] = "Smash vases",
        ["砸僵尸"] = "Smash zombies",
        ["老虎机"] = "Slot machine",
        ["松鼠"] = "Squirrel",
        ["种子雨"] = "Seed rain",
        ["迷阵"] = "Maze",
        ["快跑"] = "Sprint",
        ["传送门"] = "Portal",
        ["坚不可摧"] = "Unbreakable",
        ["排山倒海"] = "Avalanche",
        ["设置卡槽"] = "Set seed slot",
        ["设置场景"] = "Set scene",
        ["戴夫选卡数量"] = "Dave's pick count",
        ["随机选卡"] = "Random cards",
        ["查看草坪"] = "View lawn",

        // ---------- 清单：阵型 ----------
        ["切换卡组"] = "Switch deck",
        ["存储卡组"] = "Save deck",
        ["一键布阵"] = "Deploy formation",
        ["同步卡组"] = "Sync deck",
        ["存储阵型"] = "Save formation",

        // ---------- 清单：娱乐 ----------
        ["随机罐子"] = "Random vases",
        ["随机卡片"] = "Random cards",
        ["随机卡槽"] = "Random slots",
        ["手套常驻"] = "Glove always on",
        ["融合常驻"] = "Fusion always on",
        ["垃圾桶常驻"] = "Trash can always on",
        // ---------- 清单：出怪类型（40 个绰号一律用 ZombieType 枚举名，和脚本回传的英文名同源）----------
        ["普僵"] = "Normal",
        ["旗子"] = "Flag",
        ["路障"] = "TrafficCone",
        ["撑杆"] = "Polevaulter",
        ["铁桶"] = "Pail",
        ["读报"] = "Newspaper",
        ["网门"] = "Door",
        ["橄榄球"] = "Football",
        ["舞王"] = "Dancer",
        ["伴舞"] = "BackupDancer",
        ["鸭子"] = "DuckyTube",
        ["潜水"] = "Snorkel",
        ["雪橇车"] = "Zamboni",
        ["小队"] = "Bobsled",
        ["海豚"] = "DolphinRider",
        ["小丑"] = "JackInTheBox",
        ["气球"] = "Balloon",
        ["矿工"] = "Digger",
        ["蹦极"] = "Pogo",
        ["雪人"] = "Yeti",
        ["飞贼"] = "Bungee",
        ["梯子"] = "Ladder",
        ["投石车"] = "Catapult",
        ["白眼"] = "Gargantuar",
        ["小鬼"] = "Imp",
        ["僵王"] = "Boss",
        ["豌豆"] = "PeaHead",
        ["坚果"] = "WallnutHead",
        ["辣椒"] = "JalapenoHead",
        ["机枪"] = "GatlingHead",
        ["窝瓜"] = "SquashHead",
        ["高坚果"] = "TallnutHead",
        ["红眼"] = "RedeyeGargantuar",
        ["白眼机械"] = "RobotTitan",
        ["红眼机械"] = "RedeyeRobotTitan",
        ["武僧"] = "Monk",
        ["黑橄榄球"] = "FootballPremium",
        ["女忍者"] = "Ninja",
        ["天尸"] = "Talisman",
        ["螺旋桨"] = "Propeller",
        // ---------- 对话框、更新与状态管理 ----------
        ["下载并更新"] = "Download & update",
        ["下载渠道："] = "Download channels:",
        ["主花园(夜)"] = "Main garden (night)",
        ["主花园1"] = "Main garden 1",
        ["主花园2"] = "Main garden 2",
        ["仅保存"] = "Save only",
        ["保存/恢复各页签的开关、输入框、下拉框状态。首项“上次状态”为关闭时自动保存，不可删除；选中任意条目点“加载”即可恢复。"] = "Save / restore switches, inputs and dropdowns per tab. The first entry \u201clast state\u201d is saved automatically on exit and can't be deleted; select any entry and press Load to restore.",
        ["保存当前"] = "Save current",
        ["加载"] = "Load",
        ["发现新版本！"] = "New version found!",
        ["名称:"] = "Name:",
        ["密码："] = "Password:",
        ["当前版本"] = "Current version",
        ["手动查看下载"] = "Browse downloads",
        ["更新说明"] = "Release notes",
        ["检查不到更新？可随时前往"] = "Can't get an update check? You can always go to",
        ["检查更新"] = "Check for updates",
        ["植物年龄"] = "Plant age",
        ["植物朝向"] = "Plant facing",
        ["植物类型"] = "Plant type",
        ["每波一行 waveN，方括号里是 [僵尸序号, 数量]。「载入到游戏」写回关卡；「仅保存」只留在这台设备上，进关后用『载入已存波次表』灌回去。"] = "One wave per line, waveN, brackets hold [zombie index, count]. \u300cLoad into game\u300d writes it back to the level; \u300cSave only\u300d just keeps it on this device \u2014 push it in later with \u300eLoad saved wave table\u300f.",
        ["水族馆"] = "Aquarium",
        ["程序已超过使用期限，请输入密码继续使用"] = "The trial has expired; enter the password to continue",
        ["程序已过期"] = "Trial expired",
        ["编辑波次出怪 JSON"] = "Edit wave spawn JSON",
        ["花园编辑"] = "Edit garden",
        ["蘑菇园1"] = "Shroom garden 1",
        ["蘑菇园2"] = "Shroom garden 2",
        ["详细信息"] = "Details",
        ["详细信息（与默认状态对比，★ = 开启的开关）"] = "Details (vs defaults, \u2605 = switch on)",
        ["载入到游戏"] = "Load into game",
        // ---------- 对话框、更新与状态管理 ----------
        ["WebSocket地址:"] = "WebSocket address:",
        ["上次状态为空：应用尚未成功保存过状态（改动界面后退后台或退出一次即可保存）"] = "No last state yet: the app never saved one. Change something, then background or quit once.",
        ["下载更新包失败，请稍后重试"] = "Update download failed, try again later",
        ["不能使用保留名称「初始状态」或「上次状态」"] = "Can't use the reserved names \u300c\u521d\u59cb\u72b6\u6001\u300d or \u300c\u4e0a\u6b21\u72b6\u6001\u300d",
        ["写 Python 语句发给游戏"] = "Write a Python statement to send to the game",
        ["应用更新失败，请前往发布页手动下载"] = "Could not apply the update; download it from the release page",
        ["当前已是最新版本"] = "You are on the latest version",
        ["打开浏览器"] = "Open browser",
        ["断开中..."] = "Disconnecting...",
        ["无法从 GitHub / Gitee 获取版本信息，请稍后重试，或通过下方网盘渠道手动下载查看。"] = "Could not read version info from GitHub / Gitee. Try again later, or download by hand from the netdisk links below.",
        ["无法打开浏览器，请手动复制链接"] = "Couldn't open a browser; copy the link manually",
        ["服务器最新版本如上，仍可通过下方网盘渠道手动查看。"] = "The server's latest version is shown above; the netdisk links below still work.",
        ["检查更新失败"] = "Update check failed",
        ["正在下载更新"] = "Downloading update",
        ["正在从 GitHub / Gitee 检查新版本，请稍候。\n\n无论检查结果如何，都可以随时通过下方网盘渠道手动下载。"] = "Checking GitHub / Gitee for a new version, please wait.\n\nEither way you can always download by hand from the netdisk links below.",
        ["正在准备资源文件"] = "Preparing resource files",
        ["正在后台下载更新包，请稍候..."] = "Downloading the update in the background, please wait...",
        ["正在检查更新..."] = "Checking for updates...",
        ["正在解压必要资源，请稍候..."] = "Extracting required resources, please wait...",
        ["状态已应用"] = "State applied",
        ["状态服务未初始化"] = "State service not initialized",
        ["界面语言（改后要重启）"] = "Language (needs a restart)",
        ["确定要退出吗？当前设置已自动保存。"] = "Quit now? Your settings are already saved.",
        ["该方案没有保存内容"] = "This preset has no saved content",
        ["请稍后..."] = "Please wait...",
        ["请输入WebSocket地址"] = "Enter the WebSocket address",
        ["请输入方案名称"] = "Enter a preset name",
        ["跟随"] = "Follow",
        ["输入方案名称"] = "Preset name",
        ["运行"] = "Run",
        ["连接中..."] = "Connecting...",
        ["退出"] = "Exit",
        ["退出应用"] = "Exit app",
        ["选择脚本"] = "Pick a script",
        ["保存/恢复各界面的开关、输入框、下拉框状态。\n\"初始状态\"为应用默认值；\"上次状态\"为关闭时自动保存，均不可删除。"] = "Save / restore switches, inputs and dropdowns for every panel.\n\"Initial\" holds the app defaults and \"Last\" is saved automatically on exit; neither can be deleted.",
        ["更多功能"] = "More",
        ["获取新版本"] = "Get a new version",
        ["当前版本{0}"] = "Version {0}",
        ["{0}（{1}）"] = "{0} ({1})",
        ["{0}：{1}"] = "{0}: {1}",
        ["本工具完全免费"] = "This tool is and stays free",
        ["ws已连接"] = "ws connected",
        ["ws未连接"] = "ws not connected",
        ["输入URL"] = "Enter URL",
        ["GitHub（海外高速，国内可能较慢）"] = "GitHub (fast overseas, slow from mainland China)",
        ["Gitee（国内高速，推荐）"] = "Gitee (fast in China, recommended)",
        ["应用"] = "Apply",
        ["连接"] = "Connect",
        ["断开连接"] = "Disconnect",
        ["允许自动连接"] = "Allow auto connect",
        ["取消发送连接提醒"] = "Suppress connect notices",
        ["允许自动更新按钮状态"] = "Allow auto button-state refresh",
        ["启动时自动检查更新"] = "Check for updates on start",
        ["自动应用上次配置"] = "Reapply last state",
        ["界面语种"] = "Language",
        ["btn:关闭"] = "Close",          // 三态那个"关闭"是 Off，这里同字不同义
        ["取消"] = "Cancel",
        ["确定"] = "OK",
        ["设置"] = "Settings",
        ["设置已保存"] = "Settings saved",
        ["UI 风格"] = "UI style",
        ["主题（仅 NewUI 生效）"] = "Theme (NewUI only)",
        ["界面语言"] = "Language",
        ["黑夜"] = "Dark",
        ["白天"] = "Light",
        ["经典 UI"] = "Classic UI",
        ["UI 选择"] = "UI selection",
        ["密排：一行摆多个；取消：一个选项一行"] = "Compact: many per row; off: one option per row",
        ["清单里没有「{0}」这一页"] = "No \"{0}\" page in the catalog",
        ["还没有收藏，也还没点过任何功能。在任意一页的功能上长按即可收藏。"] =
            "Nothing favorited yet, and nothing tapped. Long-press a function on any page to favorite it.",
        ["收藏 / 取消收藏"] = "Favorite / unfavorite",
        ["密排"] = "Compact",
        ["脚本参数"] = "Script parameters",
        ["命中 {0} 个功能"] = "{0} functions matched",

        // ---------- 收藏页 ----------
        ["常用"] = "Frequent",
        ["点过的功能会自动按次数排到这里（最多 5 条）；一旦收藏就移上去，这里不再重复出现。"] =
            "Used functions are ranked here by how often you tap them (up to 5). " +
            "Once favorited a function moves up and stops repeating here.",
        ["还没有收藏。任意一行左侧点星标即可收藏；组里的子功能（大蒜、黄油这类）可以先搜出来再收藏。"] =
            "Nothing favorited yet. Tap the star on the left of any row; sub-functions inside a group " +
            "(garlic, butter, ...) can be searched for first and then favorited.",

        // ---------- 出怪页（先做这一页当样板；40 个僵尸绰号留给定译） ----------
        ["出怪类型"] = "Spawn types",
        ["暂停出怪"] = "Stop spawning",
        ["最大密度"] = "Max density",
        ["蹦极处理"] = "Bungee handling",
        ["红眼处理"] = "Red-eye handling",
        ["下一波"] = "Next wave",
        ["极限出怪测试"] = "Spawn stress test",
        ["同步出怪列表"] = "Sync spawn list",
        ["打印场上僵尸"] = "Print zombies on lawn",
        ["波次出怪(数量)"] = "Wave spawn (count)",
        ["波次出怪(序号)"] = "Wave spawn (index)",
        ["载入已存波次表"] = "Load saved wave table",
        ["刷新出怪血量"] = "Refresh spawn health",
        ["{0}：点一下切这个类型的出怪开关"] = "{0}: tap to toggle this type's spawning",
    };
}
