# -*- coding: utf-8 -*-
"""PvZWSTools 使用手册生成脚本(排版引擎)

手册正文内容在 同目录../手册内容.md 中编辑,本脚本只负责排版:
  1. 解析 Markdown(标题/段落/列表/表格/提示框/链接/红字);
  2. 自动生成带页码与跳转链接的目录;
  3. 渲染正文 PDF 并与封面合并。

日常改内容请编辑 手册内容.md;只有改版式(字号、颜色、页边距、封面)才需要动本文件。

Markdown 约定(详见 文档/手册编辑说明.md):
  # 章标题        ## 小节标题       普通段落(连续行合并为一段)
  - 无序列表      1. 有序列表       | 表格 | 行 |
  > 提示:...     > 注意:...        问:... / 答:...(常见问题样式)
  行内:**粗体**  !!红字!!  [文字](链接)
"""
import hashlib
import os
import re
import sys

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (CondPageBreak, PageBreak, Paragraph,
                                SimpleDocTemplate, Spacer, Table, TableStyle)
from reportlab.platypus.tableofcontents import TableOfContents

PDF_SKILL_DIR = r"C:\Users\AmourLing\.zcode\cli\plugins\cache\zcode-plugins-official\document-skills\0.1.5\skills\pdf"
BUILD_DIR = os.path.dirname(os.path.abspath(__file__))
MD_PATH = os.path.normpath(os.path.join(BUILD_DIR, "..", "手册内容.md"))
OUT_BODY = os.path.join(BUILD_DIR, "body.pdf")
OUT_COVER = os.path.join(BUILD_DIR, "cover.pdf")
OUT_FINAL = os.path.normpath(os.path.join(BUILD_DIR, "..", "使用手册.pdf"))

# ━━ Color Palette (auto-generated by design_engine.py palette-cascade, seed 23) ━━
CARD_BG = colors.HexColor('#ececea')
TABLE_STRIPE = colors.HexColor('#edece9')
BORDER = colors.HexColor('#d2cec1')
ACCENT = colors.HexColor('#2e8baa')
TEXT_PRIMARY = colors.HexColor('#151513')
TEXT_MUTED = colors.HexColor('#7f7d75')
SEM_ERROR = colors.HexColor('#a84940')
ACC_HEX = '#2e8baa'
RED_HEX = '#a84940'

# ── 封面文案(改动极少,放这里;正文内容请编辑 手册内容.md) ──
COVER = {
    'kicker': '植物大战僵尸改版玩家工具 · USER MANUAL',
    'hero': 'PvZWSTools 使用手册',
    'summary': 'PvZWSTools 通过连接游戏内脚本服务,提供出怪控制、战场编辑、阵型管理、'
               '快捷脚本等功能,支持 Windows 与 Android 双平台。本手册面向普通玩家,'
               '逐一介绍各项功能的用途与操作方法。',
    'meta': '文档版本 v1.0 · 2026 年 9 月 · 官方交流群 1034609947',
    'footer': 'PVZWSTOOLS · USER MANUAL',
    'year': '2026',
    'word': 'MANUAL',
}
COVER_PALETTE = {
    'primary': '#2e8baa', 'secondary': '#6fb3c9',
    'text': '#151513', 'muted': '#7f7d75', 'bg': '#ffffff',
}


def _cli_version():
    """release 构建时由 build-release.ps1 传入 --version <tag>,封面版本号与 tag 保持一致"""
    argv = sys.argv
    if '--version' in argv:
        i = argv.index('--version')
        if i + 1 < len(argv):
            return argv[i + 1]
    return None


MANUAL_VERSION = _cli_version()
if MANUAL_VERSION:
    COVER['meta'] = '文档版本 %s · 官方交流群 1034609947' % MANUAL_VERSION

# ── 字体：只用允许把轮廓嵌进文档的开源字体 ──
# SimSun/SimHei/微软雅黑的 OS/2.fsType 都是 0x0008（仅允许点阵嵌入），而手册 PDF 走 Release
# 附件和群文件对外分发，reportlab 嵌进去的是轮廓子集，超出它授予的范围。Noto Serif/Sans SC
# 是 SIL OFL、fsType=0x0000（可安装嵌入），对应顶替原来的宋体/黑体。
# 系统里这两个是可变字体，母版字重偏轻且 name 表自称 ExtraLight/Thin，所以先定到 wght=400
# 再喂 reportlab：一是观感回到旧版（同字号墨覆盖率实测 SimSun 3.80% / NotoSerif400 3.85%，
# SimHei 3.88% / NotoSans400 4.07%），二是 PDF 里的内嵌署名会如实写 Regular 而非 Thin。
# 必须顺手改 name 表：reportlab 按字体内部名缓存 face，不改名的不同字重会被当成同一份。
VF_FONTS = {'NotoSerifSC': 'C:/Windows/Fonts/NotoSerifSC-VF.ttf',
            'NotoSansSC': 'C:/Windows/Fonts/NotoSansSC-VF.ttf'}
FONT_DIR = os.path.join(BUILD_DIR, 'fonts')


def _instance_regular(vf_name):
    """把可变字体定到 wght=400 存成静态 TTF；生成过就复用。"""
    src = VF_FONTS[vf_name]
    if not os.path.isfile(src):
        raise SystemExit('缺少可嵌入字体 %s：%s\n'
                         '不要退回 SimSun/SimHei——它们的 fsType 禁止轮廓嵌入，'
                         '装一套 SIL OFL 的 Noto/思源中文再出手册。' % (vf_name, src))
    out = os.path.join(FONT_DIR, '%s-Regular.ttf' % vf_name)
    if os.path.isfile(out) and os.path.getmtime(out) >= os.path.getmtime(src):
        return out
    try:
        from fontTools.ttLib import TTFont as VarTTFont
        from fontTools.varLib.instancer import instantiateVariableFont
    except ImportError:
        raise SystemExit('需要 fontTools 才能把可变字体定到 400 字重：'
                         '"%s" -m pip install fonttools' % sys.executable)
    os.makedirs(FONT_DIR, exist_ok=True)
    f = VarTTFont(src)
    instantiateVariableFont(f, {'wght': 400}, inplace=True, updateFontNames=True)
    f.save(out)
    return out


BODY_FONT = 'NotoSerifSC-Regular'
HEAD_FONT = 'NotoSansSC-Regular'
BODY_PATH = _instance_regular('NotoSerifSC')
HEAD_PATH = _instance_regular('NotoSansSC')
pdfmetrics.registerFont(TTFont(BODY_FONT, BODY_PATH))
pdfmetrics.registerFont(TTFont(HEAD_FONT, HEAD_PATH))
registerFontFamily(BODY_FONT, normal=BODY_FONT, bold=HEAD_FONT, italic=BODY_FONT, boldItalic=HEAD_FONT)
registerFontFamily(HEAD_FONT, normal=HEAD_FONT, bold=HEAD_FONT, italic=HEAD_FONT, boldItalic=HEAD_FONT)

PAGE_W, PAGE_H = A4
M_LEFT = M_RIGHT = 2.2 * cm
M_TOP = 2.0 * cm
M_BOTTOM = 2.0 * cm
AVAIL_W = PAGE_W - M_LEFT - M_RIGHT
AVAIL_H = PAGE_H - M_TOP - M_BOTTOM

# ── 段落样式 ──
S_TITLE = ParagraphStyle('DocTitle', fontName=HEAD_FONT, fontSize=19, leading=27,
                         alignment=TA_CENTER, textColor=TEXT_PRIMARY, spaceAfter=12)
S_H1 = ParagraphStyle('H1', fontName=HEAD_FONT, fontSize=17, leading=25,
                      alignment=TA_CENTER, textColor=TEXT_PRIMARY,
                      spaceBefore=18, spaceAfter=10)
S_H2 = ParagraphStyle('H2', fontName=HEAD_FONT, fontSize=14, leading=20,
                      alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                      spaceBefore=14, spaceAfter=6)
S_BODY = ParagraphStyle('Body', fontName=BODY_FONT, fontSize=12, leading=20,
                        alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
                        firstLineIndent=24, spaceAfter=6, wordWrap='CJK')
S_BODY_NOIND = ParagraphStyle('BodyNoInd', parent=S_BODY, firstLineIndent=0)
S_NUM = ParagraphStyle('Num', parent=S_BODY, firstLineIndent=0, leftIndent=24,
                       spaceAfter=4)
S_BULLET = ParagraphStyle('Bullet', parent=S_BODY, firstLineIndent=0, leftIndent=18,
                          spaceAfter=3)
S_TOC_TITLE = ParagraphStyle('TocTitle', fontName=HEAD_FONT, fontSize=15, leading=22,
                             alignment=TA_CENTER, textColor=TEXT_PRIMARY,
                             spaceBefore=8, spaceAfter=8)
S_TH = ParagraphStyle('TH', fontName=HEAD_FONT, fontSize=11, leading=15.5,
                      alignment=TA_CENTER, textColor=colors.white, wordWrap='CJK')
S_TD = ParagraphStyle('TD', fontName=BODY_FONT, fontSize=11, leading=15.5,
                      alignment=TA_LEFT, textColor=TEXT_PRIMARY, wordWrap='CJK')
S_TD_C = ParagraphStyle('TDC', parent=S_TD, alignment=TA_CENTER)
S_CALLOUT = ParagraphStyle('Callout', fontName=BODY_FONT, fontSize=11, leading=17.5,
                           alignment=TA_LEFT, textColor=TEXT_PRIMARY, wordWrap='CJK')
S_FAQ_Q = ParagraphStyle('FaqQ', fontName=HEAD_FONT, fontSize=12, leading=18,
                         alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                         spaceBefore=10, spaceAfter=3)
S_CODE = ParagraphStyle('Code', fontName=BODY_FONT, fontSize=9.5, leading=13.5,
                        alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                        backColor=CARD_BG, borderPadding=(6, 8, 6, 8),
                        spaceBefore=4, spaceAfter=8)


class ManualDoc(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_key'):
            level = flowable.bookmark_level
            text = flowable.bookmark_text
            key = flowable.bookmark_key
            self.notify('TOCEntry', (level, text, self.page, key))
            try:
                self.canv.bookmarkPage(key)
                self.canv.addOutlineEntry(text, key, level=level, closed=False)
            except Exception:
                pass

    def afterPage(self):
        c = self.canv
        c.saveState()
        c.setFont(BODY_FONT, 10.5)
        c.setFillColor(TEXT_MUTED)
        c.drawCentredString(PAGE_W / 2.0, 1.1 * cm, str(c.getPageNumber()))
        c.restoreState()


# ── Markdown 行内语法 → ReportLab 行内标签 ──
def inline(text):
    t = text.replace('&', '&').replace('<', '<').replace('>', '>')
    t = re.sub(r'!!(.+?)!!',
               r'<font color="%s"><b>\1</b></font>' % RED_HEX, t)
    t = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', t)
    t = re.sub(r'\[([^\]]+)\]\(([^)\s]+)\)',
               lambda m: '<a href="%s" color="%s"><u>%s</u></a>'
                         % (m.group(2), ACC_HEX, m.group(1)), t)
    return t


def plain_width(text):
    """估算单元格显示宽度(中文 2、半角 1),用于表格列宽分配"""
    t = re.sub(r'!!|\*\*|\[([^\]]*)\]\([^)]*\)', r'\1', text)
    return sum(2 if ord(c) > 0x2E80 else 1 for c in t)


def heading(text, level):
    key = 'h_' + hashlib.md5(('%d|%s' % (level, text)).encode('utf-8')).hexdigest()[:10]
    style = S_H1 if level == 0 else S_H2
    p = Paragraph('<a name="%s"/>%s' % (key, inline(text)), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def callout(kind, text):
    if kind == 'warn':
        color, label, hex_color = SEM_ERROR, '注意', RED_HEX
    else:
        color, label, hex_color = ACCENT, '提示', ACC_HEX
    p = Paragraph('<b><font color="%s">%s</font></b>  %s' % (hex_color, label, inline(text)),
                  S_CALLOUT)
    t = Table([[p]], colWidths=[AVAIL_W], hAlign='CENTER')
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 2.5, color),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
    ]))
    return [Spacer(1, 4), t, Spacer(1, 8)]


def make_table(rows):
    ncol = max(len(r) for r in rows)
    rows = [r + [''] * (ncol - len(r)) for r in rows]
    weights = [max(plain_width(r[ci]) for r in rows) for ci in range(ncol)]
    weights = [max(w, 4) for w in weights]
    total = float(sum(weights))
    ratios = [max(w / total, 0.12) for w in weights]
    scale = 1.0 / sum(ratios)
    widths = [r * scale * AVAIL_W for r in ratios]
    center = [max(plain_width(r[ci]) for r in rows) <= 12 for ci in range(ncol)]
    data = [[Paragraph('<b>%s</b>' % inline(h), S_TH) for h in rows[0]]]
    for r in rows[1:]:
        data.append([Paragraph(inline(c), S_TD_C if center[ci] else S_TD)
                     for ci, c in enumerate(r)])
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, TABLE_STRIPE]),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    return [Spacer(1, 6), t, Spacer(1, 10)]


RE_NUM = re.compile(r'^\d+\.\s')
RE_SEP = re.compile(r'^\|[\s:\-|]+\|$')


def build_story(md_lines):
    """把 Markdown 行解析为 Flowable 列表,返回 (前言段落列表, 正文 Flowable 列表)"""
    story, intro = [], []
    seen_heading = False
    i, n = 0, len(md_lines)
    while i < n:
        s = md_lines[i].strip()
        if not s:
            i += 1
            continue
        if s.startswith('# '):
            seen_heading = True
            story.append(CondPageBreak(AVAIL_H * 0.25))
            story.append(heading(s[2:].strip(), 0))
            i += 1
        elif s.startswith('## '):
            seen_heading = True
            story.append(CondPageBreak(80))
            story.append(heading(s[3:].strip(), 1))
            i += 1
        elif s.startswith('|'):
            tbl = []
            while i < n and md_lines[i].strip().startswith('|'):
                row = md_lines[i].strip()
                if not RE_SEP.match(row):
                    tbl.append([c.strip() for c in row.strip('|').split('|')])
                i += 1
            story.extend(make_table(tbl))
        elif s.startswith('>'):
            buf = []
            while i < n and md_lines[i].strip().startswith('>'):
                buf.append(md_lines[i].strip().lstrip('>').strip())
                i += 1
            text = ''.join(buf)
            kind = 'warn' if text.startswith('注意') else 'tip'
            text = re.sub(r'^(注意|提示)[::]\s*', '', text)
            story.extend(callout(kind, text))
        elif s.startswith('```'):
            i += 1
            amp, lt, gt, nbsp = chr(38), chr(60), chr(62), chr(160)
            buf = []
            while i < n and not md_lines[i].strip().startswith('```'):
                line = md_lines[i].replace(amp, amp + 'amp;')
                line = line.replace(lt, amp + 'lt;').replace(gt, amp + 'gt;')
                line = re.sub(r'^	+', '    ', line)
                # Paragraph 折叠普通空格,行首缩进改用不换行空格保留
                line = re.sub(r'^ +', lambda m: nbsp * len(m.group()), line)
                buf.append(line)
                i += 1
            i += 1  # 跳过收尾围栏
            story.append(Paragraph('<br/>'.join(buf) if buf else nbsp, S_CODE))
        elif RE_NUM.match(s):
            items = []
            while i < n and RE_NUM.match(md_lines[i].strip()):
                items.append(RE_NUM.sub('', md_lines[i].strip()))
                i += 1
            for idx, it in enumerate(items, 1):
                story.append(Paragraph('%d. %s' % (idx, inline(it)), S_NUM))
            story.append(Spacer(1, 4))
        elif s.startswith('- '):
            items = []
            while i < n and md_lines[i].strip().startswith('- '):
                items.append(md_lines[i].strip()[2:])
                i += 1
            for it in items:
                story.append(Paragraph('•  ' + inline(it), S_BULLET))
            story.append(Spacer(1, 4))
        else:
            buf = [s]
            i += 1
            while i < n:
                t = md_lines[i].strip()
                if (not t or t.startswith(('#', '|', '- ', '>'))
                        or RE_NUM.match(t) or t.startswith(('问:', '答:'))):
                    break
                buf.append(t)
                i += 1
            text = ''.join(buf)
            if text.startswith('问:'):
                story.append(Paragraph(
                    '问:<font color="%s"><b>%s</b></font>' % (RED_HEX, inline(text[2:])),
                    S_FAQ_Q))
            elif text.startswith('答:'):
                story.append(Paragraph(inline(text), S_BODY_NOIND))
            elif not seen_heading:
                intro.append(text)
            else:
                story.append(Paragraph(inline(text), S_BODY))
    return intro, story


doc = ManualDoc(
    OUT_BODY, pagesize=A4,
    leftMargin=M_LEFT, rightMargin=M_RIGHT, topMargin=M_TOP, bottomMargin=M_BOTTOM,
    title='PvZWSTools 使用手册', author='AmourLing', creator='PvZWSTools',
    subject='PvZWSTools 玩家使用手册:功能介绍与操作说明')

with open(MD_PATH, encoding='utf-8-sig') as f:
    md_lines = f.read().splitlines()

intro, body_flow = build_story(md_lines)

story = [Paragraph('PvZWSTools 使用手册', S_TITLE)]
for p in intro:
    story.append(Paragraph(inline(p), S_BODY))
story.append(Paragraph('目 录', S_TOC_TITLE))
toc = TableOfContents()
toc.dotsMinLevel = 0
toc.levelStyles = [
    ParagraphStyle('TOC1', fontName=HEAD_FONT, fontSize=12, leading=17,
                   leftIndent=16, firstLineIndent=-16, spaceBefore=4, textColor=TEXT_PRIMARY),
    ParagraphStyle('TOC2', fontName=BODY_FONT, fontSize=11, leading=15,
                   leftIndent=34, firstLineIndent=-16, textColor=TEXT_PRIMARY),
]
story.append(toc)
story.append(PageBreak())
story.extend(body_flow)
if isinstance(story[-1], Spacer):
    story.pop()  # 表格收尾时去掉尾随间隔,避免溢出产生空白页

doc.multiBuild(story)
print('body pages OK ->', OUT_BODY)

# ══════ 封面(ReportLab 封面引擎) ══════
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, 'scripts'))
from cover_render import detect_fonts, render_cover  # noqa: E402

# 封面自己会 detect_fonts()，默认候选表里就是 SimHei/SimSun——那是插件的代码不是我们的，
# 改它会被插件更新冲掉，所以用它的 overrides 把我们这两个可嵌入字体递进去。
render_cover('01', COVER, OUT_COVER, palette=COVER_PALETTE,
             fonts=detect_fonts(overrides={'sans': (HEAD_FONT, HEAD_PATH, None),
                                           'serif': (BODY_FONT, BODY_PATH, None)}))
print('cover OK ->', OUT_COVER)

# ══════ 合并封面 + 正文(临时文件 + 原子替换,文件被占用也不会中断) ══════
from pypdf import PdfReader, PdfWriter, Transformation  # noqa: E402

A4_W, A4_H = 595.28, 841.89


def normalize(page):
    w, h = float(page.mediabox.width), float(page.mediabox.height)
    if abs(w - A4_W) > 2 or abs(h - A4_H) > 2:
        page.add_transformation(Transformation().scale(sx=A4_W / w, sy=A4_H / h))
        page.mediabox.lower_left = (0, 0)
        page.mediabox.upper_right = (A4_W, A4_H)
    return page


writer = PdfWriter()
writer.add_page(normalize(PdfReader(OUT_COVER).pages[0]))
for pg in PdfReader(OUT_BODY).pages:
    writer.add_page(normalize(pg))
writer.add_metadata({
    '/Title': 'PvZWSTools 使用手册',
    '/Author': 'AmourLing',
    '/Creator': 'PvZWSTools',
    '/Subject': 'PvZWSTools 玩家使用手册:功能介绍与操作说明',
})
tmp_path = OUT_FINAL + '.tmp'
with open(tmp_path, 'wb') as f:
    writer.write(f)
try:
    os.replace(tmp_path, OUT_FINAL)
    print('final OK ->', OUT_FINAL)
except PermissionError:
    fallback = os.path.splitext(OUT_FINAL)[0] + '_新.pdf'
    os.replace(tmp_path, fallback)
    print('final LOCKED, wrote ->', fallback)
