# -*- coding: utf-8 -*-
"""PvZWSTools 使用手册生成脚本(ReportLab 正文 + ReportLab 封面合并)

章节结构:每个界面(页签)独立成章,第4~15章依次对应主界面 12 个页签,
常见问题为第3章,状态管理/设置与获取更新为第16~17章。
"""
import hashlib
import os
import sys

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (CondPageBreak, PageBreak, Paragraph,
                                SimpleDocTemplate, Spacer, Table, TableStyle)
from reportlab.platypus.tableofcontents import TableOfContents

PDF_SKILL_DIR = r"C:\Users\AmourLing\.zcode\cli\plugins\cache\zcode-plugins-official\document-skills\0.1.5\skills\pdf"
BUILD_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_BODY = os.path.join(BUILD_DIR, "body.pdf")
OUT_COVER = os.path.join(BUILD_DIR, "cover.pdf")
OUT_FINAL = os.path.normpath(os.path.join(BUILD_DIR, "..", "使用手册.pdf"))

# ━━ Color Palette (auto-generated by design_engine.py palette-cascade, seed 23) ━━
PAGE_BG = colors.HexColor('#f3f2f1')
SECTION_BG = colors.HexColor('#ecebe9')
CARD_BG = colors.HexColor('#ececea')
TABLE_STRIPE = colors.HexColor('#edece9')
BORDER = colors.HexColor('#d2cec1')
ACCENT = colors.HexColor('#2e8baa')
ACCENT_2 = colors.HexColor('#57be57')
TEXT_PRIMARY = colors.HexColor('#151513')
TEXT_MUTED = colors.HexColor('#7f7d75')
SEM_ERROR = colors.HexColor('#a84940')
SEM_INFO = colors.HexColor('#426a92')
ACC_HEX = '#2e8baa'
RED_HEX = '#a84940'

# ── 字体(本机字体优先) ──
pdfmetrics.registerFont(TTFont('SimSun', 'C:/Windows/Fonts/simsun.ttc', subfontIndex=0))
pdfmetrics.registerFont(TTFont('SimHei', 'C:/Windows/Fonts/simhei.ttf'))
registerFontFamily('SimSun', normal='SimSun', bold='SimHei', italic='SimSun', boldItalic='SimHei')
registerFontFamily('SimHei', normal='SimHei', bold='SimHei', italic='SimHei', boldItalic='SimHei')

PAGE_W, PAGE_H = A4
M_LEFT = M_RIGHT = 2.2 * cm
M_TOP = 2.0 * cm
M_BOTTOM = 2.0 * cm
AVAIL_W = PAGE_W - M_LEFT - M_RIGHT
AVAIL_H = PAGE_H - M_TOP - M_BOTTOM

# ── 段落样式 ──
S_TITLE = ParagraphStyle('DocTitle', fontName='SimHei', fontSize=17, leading=24,
                         alignment=TA_CENTER, textColor=TEXT_PRIMARY, spaceAfter=10)
S_H1 = ParagraphStyle('H1', fontName='SimHei', fontSize=15, leading=22,
                      alignment=TA_CENTER, textColor=TEXT_PRIMARY,
                      spaceBefore=18, spaceAfter=10)
S_H2 = ParagraphStyle('H2', fontName='SimHei', fontSize=12.5, leading=18,
                      alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                      spaceBefore=14, spaceAfter=6)
S_BODY = ParagraphStyle('Body', fontName='SimSun', fontSize=10.5, leading=17.5,
                        alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
                        firstLineIndent=21, spaceAfter=6, wordWrap='CJK')
S_BODY_NOIND = ParagraphStyle('BodyNoInd', parent=S_BODY, firstLineIndent=0)
S_NUM = ParagraphStyle('Num', parent=S_BODY, firstLineIndent=0, leftIndent=22,
                       spaceAfter=4)
S_BULLET = ParagraphStyle('Bullet', parent=S_BODY, firstLineIndent=0, leftIndent=16,
                          spaceAfter=3)
S_TOC_TITLE = ParagraphStyle('TocTitle', fontName='SimHei', fontSize=14, leading=20,
                             alignment=TA_CENTER, textColor=TEXT_PRIMARY,
                             spaceBefore=8, spaceAfter=8)
S_TH = ParagraphStyle('TH', fontName='SimHei', fontSize=9.5, leading=13.5,
                      alignment=TA_CENTER, textColor=colors.white, wordWrap='CJK')
S_TD = ParagraphStyle('TD', fontName='SimSun', fontSize=9.5, leading=13.5,
                      alignment=TA_LEFT, textColor=TEXT_PRIMARY, wordWrap='CJK')
S_TD_C = ParagraphStyle('TDC', parent=S_TD, alignment=TA_CENTER)
S_CALLOUT = ParagraphStyle('Callout', fontName='SimSun', fontSize=9.5, leading=15.5,
                           alignment=TA_LEFT, textColor=TEXT_PRIMARY, wordWrap='CJK')
S_FAQ_Q = ParagraphStyle('FaqQ', fontName='SimHei', fontSize=10.5, leading=16,
                         alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                         spaceBefore=10, spaceAfter=3)
S_FOOT = ParagraphStyle('Foot', fontName='SimSun', fontSize=9, leading=12,
                        alignment=TA_CENTER, textColor=TEXT_MUTED)


def red(t):
    return '<font color="%s"><b>%s</b></font>' % (RED_HEX, t)


def acc(t):
    return '<font color="%s"><b>%s</b></font>' % (ACC_HEX, t)


def link(url, label=None):
    return '<a href="%s" color="%s"><u>%s</u></a>' % (url, ACC_HEX, label or url)


class ManualDoc(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_key'):
            level = flowable.bookmark_level
            text = flowable.bookmark_text
            key = flowable.bookmark_key
            self.notify('TOCEntry', (level, text, self.page, key))
            try:
                self.canv.bookmarkPage(key)
                self.canv.addOutlineEntry(text, key, level=level, closed=False)
            except Exception:
                pass

    def afterPage(self):
        c = self.canv
        c.saveState()
        c.setFont('SimSun', 9)
        c.setFillColor(TEXT_MUTED)
        c.drawCentredString(PAGE_W / 2.0, 1.1 * cm, str(c.getPageNumber()))
        c.restoreState()


def heading(text, level):
    key = 'h_' + hashlib.md5(('%d|%s' % (level, text)).encode('utf-8')).hexdigest()[:10]
    style = S_H1 if level == 0 else S_H2
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def add_heading(story, text, level):
    if level == 0:
        story.append(CondPageBreak(AVAIL_H * 0.25))
        story.append(heading(text, 0))
    elif level == 1:
        story.append(CondPageBreak(80))
        story.append(heading(text, 1))
    else:
        story.append(CondPageBreak(60))
        story.append(heading(text, 2))


def body(story, text, style=None):
    story.append(Paragraph(text, style or S_BODY))


def bullets(story, items):
    for it in items:
        story.append(Paragraph('•  ' + it, S_BULLET))
    story.append(Spacer(1, 4))


def steps(story, items):
    for i, it in enumerate(items, 1):
        story.append(Paragraph('%d. %s' % (i, it), S_NUM))
    story.append(Spacer(1, 4))


def make_table(story, headers, rows, ratios, center_cols=(), keep=True):
    widths = [r * AVAIL_W for r in ratios]
    data = [[Paragraph('<b>%s</b>' % h, S_TH) for h in headers]]
    for row in rows:
        cells = []
        for ci, c in enumerate(row):
            cells.append(Paragraph(c, S_TD_C if ci in center_cols else S_TD))
        data.append(cells)
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, TABLE_STRIPE]),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(Spacer(1, 6))
    story.append(t)
    story.append(Spacer(1, 10))


def callout(story, kind, text):
    if kind == 'warn':
        color, label, hex_color = SEM_ERROR, '注意', RED_HEX
    else:
        color, label, hex_color = ACCENT, '提示', ACC_HEX
    p = Paragraph('<b><font color="%s">%s</font></b>  %s' % (hex_color, label, text),
                  S_CALLOUT)
    t = Table([[p]], colWidths=[AVAIL_W], hAlign='CENTER')
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 2.5, color),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
    ]))
    story.append(Spacer(1, 4))
    story.append(t)
    story.append(Spacer(1, 8))


# ══════════════ 文档组装 ══════════════
doc = ManualDoc(
    OUT_BODY, pagesize=A4,
    leftMargin=M_LEFT, rightMargin=M_RIGHT, topMargin=M_TOP, bottomMargin=M_BOTTOM,
    title='PvZWSTools 使用手册', author='AmourLing', creator='PvZWSTools',
    subject='PvZWSTools 玩家使用手册:功能介绍与操作说明')

story = []

# ── 首页:标题 + 手册说明 + 目录 ──
story.append(Paragraph('PvZWSTools 使用手册', S_TITLE))
body(story, 'PvZWSTools 是一款为 PGvZ、PvZ.net 等植物大战僵尸改版游戏打造的玩家辅助工具,'
            '支持 Windows 与 Android 双平台。工具通过连接游戏内建的脚本服务即可使用各项功能,'
            '提供出怪控制、战场编辑、阵型管理、快捷脚本等丰富玩法辅助,无需修改任何游戏文件。')
body(story, '使用中遇到问题,欢迎加入官方交流群(%s)提问。提问时建议附上软件截图与游戏完整截图,'
            '并说明所用的软件版本、游戏版本与操作步骤,以便更快定位问题。' % red('1034609947'))
body(story, '为便于阅读,本手册约定:按钮、页签等界面元素以『』标注;正文中带底色的'
            '“提示”“注意”方框,分别为使用技巧与需要留意的事项。本手册面向普通玩家,'
            '不涉及脚本编写等开发内容;如需了解二次开发,请前往 GitHub 仓库查阅相关文档。'
            '第4章至第15章按主界面页签顺序,逐章介绍 12 个功能页签。')
story.append(Paragraph('目 录', S_TOC_TITLE))
toc = TableOfContents()
toc.dotsMinLevel = 0
toc.levelStyles = [
    ParagraphStyle('TOC1', fontName='SimHei', fontSize=10.5, leading=15,
                   leftIndent=14, firstLineIndent=-14, spaceBefore=4, textColor=TEXT_PRIMARY),
    ParagraphStyle('TOC2', fontName='SimSun', fontSize=9.5, leading=13.2,
                   leftIndent=30, firstLineIndent=-14, textColor=TEXT_PRIMARY),
]
story.append(toc)
story.append(PageBreak())

# ══════ 第 1 章 ══════
add_heading(story, '第1章 认识 PvZWSTools', 0)
add_heading(story, '1.1 软件简介', 1)
body(story, 'PvZWSTools(玩家俗称 WS 工具)通过 WebSocket 与游戏内建的脚本服务通信:'
            '工具界面上每一个按钮、每一个开关,都对应一段发送给游戏执行的指令,'
            '由游戏实时完成对应效果。因此工具不需要写入或修改游戏文件,'
            '游戏更新后一般也只需更新脚本配置即可继续使用。')
body(story, '软件分为 Windows 版与 Android 版,两端功能基本一致:电脑端适合边玩边改,'
            '手机端可以在同一局域网内连接电脑游戏,也能连接手机上的模拟器。'
            '两端界面形态与部分按钮名称有所差异,对照详见 1.4。')
add_heading(story, '1.2 功能一览', 1)
body(story, '工具主界面共 12 个功能页签,覆盖从基础开关到深度玩法的各个方面:')
make_table(story, ['页签', '主要用途'], [
    ['杂项', '游戏速度、清除迷雾、自动收集、取消冷却等常用全局开关'],
    ['关卡', '切换关卡模式、设置无尽旗数、直接过关等关卡控制'],
    ['资源', '修改阳光、金钱,以及植物僵尸的价值、伤害、血量、时间等数值'],
    ['植物', '植物无敌、快速准备、清醒、血量显示等植物强化开关'],
    ['僵尸', '僵尸无敌、停滞、一键魅惑等僵尸行为开关'],
    ['出怪', '控制每波出现哪些僵尸、出怪节奏,自定义波次出怪表'],
    ['战场', '在草坪上任意摆放植物、僵尸、物品与道具,管理小推车与存档'],
    ['挑战', '一键开启砸罐子、我是僵尸、老虎机等挑战玩法'],
    ['阵型', '一键布阵、存储阵型,管理卡组、卡槽与选卡'],
    ['娱乐', '随机罐子、随机卡槽等趣味玩法开关'],
    ['快捷脚本', '运行内置脚本,带说明与参数输入界面'],
    ['花园', '管理主花园、蘑菇园、水族馆等场景中的植物(仅 Windows 端提供)'],
], [0.2, 0.8], center_cols=(0,))
add_heading(story, '1.3 使用前的准备', 1)
bullets(story, [
    '游戏端需使用支持脚本服务的改版版本(如 PGvZ、PvZ.net 等整合了脚本服务的 MOD),并在游戏内开启对应服务;',
    '建议工具与游戏保持版本配套,遇到兼容问题时优先把两侧都更新到最新版;',
    'Android 端需允许应用联网;使用模拟器时,手机端工具与模拟器需网络互通。',
])

add_heading(story, '1.4 两端差异对照', 1)
body(story, 'Windows 端与 Android 端的核心功能一致,主要差异如下,使用前请先了解自己所用端的形式:')
make_table(story, ['项目', 'Windows 端', 'Android 端'], [
    ['界面形态', '顶部连接栏 + 12 个功能页签 + 底部功能栏',
     '侧滑抽屉导航,『连接』为独立页面'],
    ['功能页面', '12 个页签,含花园页', '12 个页面,无花园页,多独立『连接』页'],
    ['状态管理 / 设置 / 更新入口', '底部『状态管理』『环境』『获取更新』按钮',
     '抽屉"更多功能"组:状态管理、设置、获取新版本'],
    ['打开文件目录 / 界面缩放', '底部按钮支持', '无此功能'],
    ['波次出怪 json 编辑', '勾选『json编辑』后调用系统编辑器', '勾选后在应用内编辑'],
    ['首次启动', '安装后即用', '首次启动需等待解压资源("正在准备资源文件")'],
], [0.24, 0.38, 0.38])

# ══════ 第 2 章 ══════
add_heading(story, '第2章 下载、安装与连接游戏', 0)
add_heading(story, '2.1 下载安装包', 1)
body(story, 'PvZWSTools 可通过以下渠道下载,内容一致,选择下载速度快的即可:')
make_table(story, ['渠道', '地址'], [
    ['官方 QQ 群', '1034609947(群文件)'],
    ['百度网盘', link('https://pan.baidu.com/s/1UibnjHtCUx6ygEJpO3jbpQ?pwd=LING', 'pan.baidu.com/s/1UibnjHtCUx6ygEJpO3jbpQ 提取码 LING')],
    ['夸克网盘', link('https://pan.quark.cn/s/b05452efdd9d', 'pan.quark.cn/s/b05452efdd9d')],
    ['迅雷云盘', link('https://pan.xunlei.com/s/VP1mIwIh5ejBzPUkFl61vqebA1', 'pan.xunlei.com/s/VP1mIwIh5ejBzPUkFl61vqebA1')],
    ['移动云盘', link('https://yun.139.com/shareweb/#/w/i/2xTrEZYJmLtyn', 'yun.139.com/shareweb/#/w/i/2xTrEZYJmLtyn')],
    ['UC 网盘', link('https://drive.uc.cn/s/23bbc188ce1c4', 'drive.uc.cn/s/23bbc188ce1c4')],
    ['GitHub Releases', link('https://github.com/AmourLing/PvZWSTools/releases', 'github.com/AmourLing/PvZWSTools/releases')],
], [0.28, 0.72])
body(story, '下载页面中会有多个文件,按设备选择对应安装包即可:')
make_table(story, ['文件', '说明'], [
    ['PvZWSTools_windows_setup.exe', 'Windows 电脑安装包,电脑用户下载这个'],
    ['PvZWSTools_android.APK', 'Android 手机安装包,手机用户下载这个'],
    ['PvZWSTools_windows_self-contained.zip', 'Windows 免安装压缩包,普通用户不用管'],
    ['PvZWSTools_windows_framework-dependent.zip', 'Windows 免安装压缩包,普通用户不用管'],
], [0.56, 0.44])
add_heading(story, '2.2 安装与首次启动', 1)
body(story, red('Windows 端') + ':双击安装包,按提示完成安装即可。'
            '工具不需要放进游戏目录,可安装在任意位置;阵型、脚本等配置文件保存在程序运行目录旁的'
            '『配置文件』文件夹中,可随时通过底部『打开文件目录』按钮打开。')
body(story, red('Android 端') + ':安装 APK 前需允许安装未知来源应用。'
            '首次启动会出现『正在准备资源文件』提示,这是在解压内置的脚本与配置资源,'
            '等待完成后即可正常使用,请勿强制关闭。')
add_heading(story, '2.3 连接游戏', 1)
body(story, '绝大多数功能都需要先连接游戏,步骤如下:')
steps(story, [
    '启动游戏并进入存档,确认所用改版已开启脚本服务(一般可在游戏 MOD 菜单中开启);',
    '打开 PvZWSTools。Windows 端顶部地址栏默认为 ws://localhost:8080/Py;'
    'Android 端打开抽屉中的『连接』页,在地址框填入地址。本机游戏直接使用默认地址;'
    '手机连电脑上的模拟器时,把地址改为电脑的局域网 IP,例如 ws://192.168.1.5:8080/Py;',
    '点击『连接』。连接成功后按钮变为『断开连接』,游戏内会弹出"已成功与PvZWSTools连接"的提示。',
])
callout(story, 'warn',
        '如果连接失败:工具会自动依次尝试 8080、8081、8082 三个端口;仍失败时请检查游戏是否已经启动、'
        '脚本服务是否开启、防火墙是否拦截,手机端还需确认已允许应用联网。'
        '可在『环境』(Android 端为『设置』)中勾选『允许自动连接』,工具会自动反复尝试,直到连上为止。')
add_heading(story, '2.4 主界面一览', 1)
body(story, red('Windows 端') + ':顶部为 WebSocket 地址栏与『连接』按钮;中间是 12 个功能页签;'
            '底部一排常用入口:')
bullets(story, [
    '『获取更新』:检查并安装新版本(详见第17章);',
    '『打开文件目录』:打开配置文件所在文件夹,阵型、快捷脚本、选项都在里面;',
    '『状态管理』:保存与恢复各页签的开关、输入框状态(详见第16章);',
    '『界面缩放』:点击 + / - 调整界面大小,默认 100%;',
    '『环境』:打开软件设置(详见第16章)。',
])
body(story, red('Android 端') + ':采用侧滑抽屉导航,从屏幕左缘向右滑(或点击左上角菜单图标)打开抽屉。'
            '抽屉上半部分是 12 个功能页(杂项至快捷脚本)与『连接』页;'
            '"更多功能"分组提供『状态管理』『设置』『获取新版本』,'
            '底部同时显示当前版本号。')

# ══════ 第 3 章 常见问题(前移,方便随查随用) ══════
add_heading(story, '第3章 常见问题', 0)
body(story, '本章整理了使用中最常遇到的问题与解决方法;各项功能的完整介绍,'
            '将从第4章开始按页签顺序逐一展开,遇到问题时也可随时回到本章查找。')
faqs = [
    ('点击『连接』提示连接失败?',
     '请确认游戏已经启动、所用改版支持并开启了脚本服务;工具会自动尝试 8080、8081、8082 三个端口,'
     '若仍失败请检查防火墙是否拦截。手机端需允许应用联网;手机连接电脑模拟器时,'
     '地址要写电脑的局域网 IP 而不是 localhost。'),
    ('点按钮提示 WebSocket 未连接?',
     '说明尚未连接游戏或连接已断开。先点击顶部『连接』,看到游戏内弹出连接成功提示后再操作。'),
    ('提示"脚本文件不存在"?',
     '工具依赖运行目录旁的『配置文件』文件夹。请勿单独移动主程序,'
     '建议重新解压完整压缩包;Android 端重装应用即可重新释放资源。'),
    ('界面开关和游戏里的实际效果对不上?',
     '在杂项页点『更新按钮状态』同步一次(Windows 端,见第4章);'
     'Android 端开启『允许自动更新按钮状态』后切换页面即自动同步。'
     '也可在『环境』或『设置』中开启该选项(见第16章)。'),
    ('载入波次出怪时提示文件不存在?',
     '先在关卡内执行一次『波次出怪(数量)』导出 ZombiesInWave.json,再编辑、载入(详见第9章)。'),
    ('打开工具提示"程序已过期"?',
     '测试版有效期为发布后 14 天。过期窗口中可点击『检查更新』进入仅更新模式获取新版,'
     '或到官方群、网盘下载最新正式版。'),
    ('存储阵型时名称重复会覆盖吗?',
     '不会。重名阵型会自动追加 _1 后缀另存;想删除阵型,到『配置文件/阵型』文件夹删除对应'
     ' json 文件即可(阵型功能详见第12章)。'),
    ('手机首次启动一直显示"正在准备资源文件"?',
     '这是在解压内置脚本资源,视手机性能需要等待片刻,请保持前台等待完成,不要强制关闭。'),
    ('游戏突然闪退怎么办?',
     '可先运行快捷脚本『尝试取消异常报错闪退』缓解;若仍复现,请到官方群反馈,'
     '并附上操作步骤与相关截图。'),
    ('想把自己的阵型、出怪配置分享给朋友?',
     '把『配置文件/阵型』下的阵型 json、『配置文件/出怪』下的波次 json 发给对方,'
     '放进相同位置的文件夹即可直接使用。'),
]
for q, a in faqs:
    story.append(Paragraph('问:' + red(q), S_FAQ_Q))
    story.append(Paragraph('答:' + a, S_BODY_NOIND))

# ══════ 第 4 章 杂项页 ══════
add_heading(story, '第4章 杂项页:常用全局开关', 0)
body(story, '杂项页汇集了最常用的全局开关,点击即开启、再次点击即关闭,效果实时生效。')
add_heading(story, '4.1 开关一览', 1)
make_table(story, ['开关', '作用'], [
    ['清除迷雾', '去除浓雾关卡与夜间关卡中的雾,视野一目了然'],
    ['罐子透视', '罐子变半透明,可直接看到里面的内容,砸罐子模式利器'],
    ['阳光增值', '提高阳光的产出价值'],
    ['自动收集', '自动拾取阳光、金币、奖杯等掉落物'],
    ['取消冷却', '卡片冷却立即结束,可以连续种植'],
    ['自动浇水', '花园中的植物自动浇水,无需手动照料'],
    ['取消阳光', '种植不消耗阳光,任意铺场'],
    ['后台运行', '游戏窗口在后台时照常运行,方便挂机'],
    ['去除遮挡', '移除挡住草坪的界面元素,视野更清爽'],
    ['补充肥料杀虫剂', '把花园的肥料与杀虫剂补满'],
], [0.28, 0.72])
add_heading(story, '4.2 游戏速度与智慧树', 1)
body(story, '『游戏速度』下拉框可在 1/10、1/2、1、2、3、5、10 倍之间切换,选择后立即生效;'
            '想恢复正常速度选回 1 即可。配合快捷脚本页中的多个速度脚本,还能获得更多变速档位。')
body(story, '在『设置树的高度』左侧输入框中填入数值,点击按钮即可把智慧树设置为指定高度,'
            '直接听取高等级智慧树提示。')
add_heading(story, '4.3 同步开关状态', 1)
body(story, '如果手动在游戏或其他途径改变了状态,界面开关可能与游戏内实际效果不一致。'
            'Windows 端点击『更新按钮状态』,工具会从游戏读取各开关的真实状态并刷新显示;'
            'Android 端没有单独的按钮,在『设置』中开启『允许自动更新按钮状态』后,'
            '切换页面时会自动完成同步。')
callout(story, 'tip',
        '建议在『环境』(Android 端为『设置』)中开启『允许自动更新按钮状态』,'
        '切换页签时工具会自动同步,免去手动刷新。')

# ══════ 第 5 章 关卡页 ══════
add_heading(story, '第5章 关卡页:关卡控制', 0)
body(story, '关卡页用于切换与控制当前关卡,各按钮功能如下:')
make_table(story, ['按钮', '作用'], [
    ['设置模式', '下拉选择目标关卡模式(如冒险模式),配合『EnterNewLevel』使用'],
    ['设置无尽旗数', '设置无尽模式要挑战的旗数,默认 2333'],
    ['EnterNewLevel', '按当前『设置模式』进入对应的新关卡'],
    ['直接过关', '立即完成当前关卡,直接结算'],
    ['混乱关卡', '开启后关卡参数随机乱套,体验混乱效果,整活向'],
], [0.28, 0.72], center_cols=(0,))

# ══════ 第 6 章 资源页 ══════
add_heading(story, '第6章 资源页:资源与数值', 0)
body(story, '上半部分四个按钮:在输入框填入数值后,分别点击『设置阳光』『设置阳光上限』'
            '『设置金钱』『设置金钱上限』,立即改写对应资源。')
body(story, '下半部分为进阶修改:『设置价值』『设置伤害』『设置血量』『设置时间』。'
            '先在左侧下拉框选择要修改的对象(如某种植物或僵尸),再输入数值执行,'
            '即可修改场上对应单位的属性。下拉候选内容保存于『配置文件/选项』文件夹的 json 文件中,'
            '有需要可自行增改。')

# ══════ 第 7 章 植物页 ══════
add_heading(story, '第7章 植物页:植物增强', 0)
body(story, '植物页集中了植物相关的强化开关,点击即开启、再次点击关闭:')
make_table(story, ['开关', '作用'], [
    ['植物无敌', '植物不再受到任何伤害'],
    ['植物清醒', '植物不再睡觉,蘑菇类白天也能直接种植使用'],
    ['核弹无坑', '爆炸类植物使用后不在地面留下弹坑'],
    ['只投黄油', '投手类植物只投出黄油,持续定身控场'],
    ['取消压扁', '一键恢复被僵尸压扁的植物'],
    ['植物血量显示', '在植物上方显示血量数值'],
    ['准备时间显示', '显示卡片装填与植物准备的剩余时间'],
    ['路灯花觉醒', '让路灯花立即进入觉醒状态'],
    ['伞弹车常驻', '让伞、炮弹、小推车类单位常驻可用'],
    ['快速准备系列', '土豆雷、大嘴花、阳光菇、磁力菇、玉米炮、超级大嘴花等一键就绪'],
    ['其他植物准备时间', '统一缩短其余植物的准备时间'],
    ['龙舌兰大招 / 火红莲大招', '立即触发对应植物的强力大招'],
], [0.32, 0.68])

# ══════ 第 8 章 僵尸页 ══════
add_heading(story, '第8章 僵尸页:僵尸控制', 0)
body(story, '僵尸页集中了僵尸行为相关的开关:')
make_table(story, ['开关', '作用'], [
    ['僵尸无敌', '僵尸不再受到任何伤害'],
    ['停滞不前', '场上僵尸原地停止移动'],
    ['冰车无痕', '冰车僵尸铺路不再留下冰道'],
    ['丑椒不爆', '丑椒不再自爆'],
    ['僵尸血量显示', '在僵尸上方显示血量数值'],
    ['僵尸掉落卡片', '击杀僵尸时有概率掉落卡片奖励'],
    ['小偷不偷', '小偷僵尸不再偷取植物'],
    ['限制减益', '解除相关负面效果限制'],
], [0.32, 0.68])
body(story, '页面下方提供『一键魅惑效果』『一键大蒜效果』『一键黄油效果』『一键冰封效果』四个批量按钮,'
            '可把场上的僵尸批量转变为对应状态;『允许魅惑』子开关用于控制魅惑是否生效。'
            '搭配『僵尸无敌』『停滞不前』等开关,可以摆出各种趣味场面。')

# ══════ 第 9 章 出怪页 ══════
add_heading(story, '第9章 出怪页:出怪控制', 0)
add_heading(story, '9.1 选择出场的僵尸', 1)
body(story, '出怪页列出全部 40 种僵尸,每种僵尸一个开关:打开即允许该僵尸出现,关闭则不再刷新。'
            '想打造纯某种僵尸的关卡,把其他僵尸全部关掉即可。')
body(story, 'Windows 端还可点击『获取当前出怪』,从游戏读取当前关卡的出怪配置并刷新开关显示;'
            '点击『打印场上僵尸』可在日志中列出当前场上所有僵尸,方便排查(Android 端暂无这两个按钮)。')
add_heading(story, '9.2 出怪节奏', 1)
make_table(story, ['开关 / 按钮', '作用'], [
    ['暂停出怪', '暂停刷怪,场上不再出现新僵尸;再次点击恢复'],
    ['最大密度', '设置同一时间场上的僵尸数量上限'],
    ['下一波', '立即触发下一波刷新,不用等红字提示'],
], [0.3, 0.7], center_cols=(0,))
add_heading(story, '9.3 自定义每波出怪(波次出怪)', 1)
body(story, '想把每一波出什么怪、出多少完全掌控,可以使用波次出怪功能:')
steps(story, [
    '点击『波次出怪(数量)』,工具把当前关卡的出怪安排导出为 配置文件/出怪/ZombiesInWave.json;',
    '勾选『json编辑』后再次点击,会自动打开编辑器:Windows 端调用系统编辑器,Android 端在应用内编辑;',
    '按文件内的格式修改每一波各类僵尸的数量,保存文件;',
    '点击『载入json』把修改后的波次表写回游戏,之后的每一波都会按你的设置刷新。',
])
body(story, '『波次出怪(序号)』则以序号方式查看与调整各波内容,适合精细微调。')
callout(story, 'warn',
        '提示"波次出怪文件不存在"时,请先执行一次『波次出怪(数量)』完成导出,再进行编辑与载入。'
        '另外需处于关卡内导出的数据才有效。')
add_heading(story, '9.4 血量与特殊僵尸处理', 1)
make_table(story, ['功能', '作用'], [
    ['刷新血量', '按输入的最小、最大比例(默认 0.5 至 0.65)重新设定出怪僵尸的血量浮动范围'],
    ['蹦极红眼处理', '针对蹦极僵尸与红眼僵尸的特殊处理开关,避免干扰布局'],
    ['极限出怪测试', '以极限参数压测出怪,用于测试阵型强度'],
], [0.3, 0.7], center_cols=(0,))

# ══════ 第 10 章 战场页 ══════
add_heading(story, '第10章 战场页:战场编辑', 0)
add_heading(story, '10.1 摆放植物、僵尸与物品', 1)
body(story, '战场页把草坪抽象为 6 行 9 列的网格(也提供『全部行』『全部列』快速选择)。'
            '先选好行列,再从下拉中选择内容,点击对应按钮即可放置:')
bullets(story, [
    '『放置植物』:放置所选植物,可附加勾选模仿者版本、限制状态、沉睡状态;',
    '『放置僵尸』:在所选列放置所选僵尸,可勾选魅惑状态直接为我所用;',
    '『放置物品』:放置墓石、银币等场景物品;',
    '『放置道具』:放置罐子等道具,可选择罐子类型与状态;',
    '『清除』:清空所选行列上的内容。',
])
add_heading(story, '10.2 小推车与种植辅助', 1)
bullets(story, [
    '小推车:对所选行的小推车执行触发、恢复、删除操作;',
    '『一键搭梯』:在指定位置搭好梯子,方便蹦极与运镜玩法;',
    '『自由种植』:解除种植限制,在任意位置任意植物;',
    'EasyPlanting:简化种植流程的辅助开关。',
])
add_heading(story, '10.3 存档与回档', 1)
body(story, '『立即存档』保存当前战场快照;折腾之后点『立即回档』即可一键恢复到存档时刻;'
            '『禁止存档』可阻止游戏自身写入存档,避免测试数据污染进度。'
            '搭配第9章的出怪控制与第12章的阵型布阵,可以反复演练同一波攻势。')

# ══════ 第 11 章 挑战页 ══════
add_heading(story, '第11章 挑战页:挑战玩法', 0)
body(story, '挑战页提供一键进入各类经典玩法模式的按钮:'
            '风暴、传送带、砸罐子、砸僵尸、IZombie(我是僵尸)、老虎机、松鼠、排山倒海,'
            '以及『其他挑战』(包含更多玩法入口)。点击按钮即可切换到对应玩法,再次点击可取消。')

# ══════ 第 12 章 阵型页 ══════
add_heading(story, '第12章 阵型页:阵型与卡组', 0)
add_heading(story, '12.1 一键布阵', 1)
body(story, '在阵型页顶部的下拉框选择阵型,点击『一键布阵』,工具会自动在草坪上种好整套阵型,'
            '数秒内完成摆场。阵型文件保存在『配置文件/阵型』文件夹,是通用的 json 文件——'
            '把别人分享的阵型文件放进去,重新打开下拉框即可看到并使用。')
add_heading(story, '12.2 存储阵型', 1)
body(story, '在场上摆好阵后,输入阵型名称,勾选要保存的内容(储存植物、储存梯子、储存罐子),'
            '点击『存储阵型』即可把当前局面完整保存为阵型文件。名称重复时会自动追加 _1 后缀,不会覆盖旧阵型。')
callout(story, 'tip',
        '先『一键布阵』再手动微调,之后『存储阵型』,是沉淀自己常用阵型的最快方式。')
add_heading(story, '12.3 卡组管理', 1)
body(story, '『切换卡组』『存储卡组』用于保存与恢复卡片配置;『同步卡组』把当前卡组与阵型联动,'
            '布阵的同时把卡槽换成配套卡组,一步到位(目前仅 Windows 端提供)。')
add_heading(story, '12.4 卡槽与选卡', 1)
bullets(story, [
    '『设置卡槽』:选择卡槽序号与植物(可含模仿者),精确改写某个卡槽;',
    '『戴夫选卡』:自动完成选卡。数量含义:0 为不选卡,1 至 3 为保留原生选卡,4 至 10 为扩展随机选卡;',
    '『随机选卡』:随机生成一套选卡。',
])
add_heading(story, '12.5 场景与草坪', 1)
bullets(story, [
    '『设置场景』:切换草坪场景(白天、草地、裸地等);',
    '『查看草坪』:从游戏读取当前草坪布置,便于核对;',
    '『设置道路状况』:调整草地道路状态,可勾选同步格子一起生效;',
    '『设置格子类型』:修改指定格子的类型(如改为水池等)。',
])

# ══════ 第 13 章 娱乐页 ══════
add_heading(story, '第13章 娱乐页:娱乐开关', 0)
body(story, '娱乐页提供以下趣味玩法开关,点击即开启、再次点击关闭:')
make_table(story, ['开关', '作用'], [
    ['随机罐子', '罐子里开出什么全凭运气'],
    ['随机卡片', '选卡界面随机变化'],
    ['随机卡槽', '卡槽内容随机刷新'],
    ['手套常驻 / 融合常驻 / 垃圾桶常驻', '让手套、融合、垃圾桶等常用小工具常驻可用'],
], [0.42, 0.58])

# ══════ 第 14 章 快捷脚本页 ══════
add_heading(story, '第14章 快捷脚本页', 0)
add_heading(story, '14.1 运行快捷脚本', 1)
body(story, '快捷脚本页会列出『配置文件/快捷脚本』文件夹中的全部脚本。使用方法:')
steps(story, [
    '在列表中点击选中一个脚本,页面会显示它的功能说明与作者;',
    '若脚本带有参数,下方会出现输入框或下拉框,并给出参数说明与默认值;',
    '按说明填写参数后点击『执行』,脚本即发送到游戏中运行,效果实时生效。',
])
callout(story, 'tip',
        '执行任何脚本前请先连接游戏;脚本的参数配置与脚本同名(如 脚本名.py.config.json),'
        '一般无需手动修改。')
add_heading(story, '14.2 常用快捷脚本一览', 1)
make_table(story, ['脚本', '功能'], [
    ['游戏速度', '快速切换全局游戏速度'],
    ['戴夫选卡', '自动完成戴夫选卡,数量可选 0 至 10'],
    ['阵型转化', '粘贴阵型代码,一键转化为场上布阵'],
    ['存储阵型', '导出当前场上的植物与梯子布置'],
    ['NextWaveButton', '在棋盘上添加一个『下一波』按钮,点按即触发下一波'],
    ['修改完成冒险次数', '修改冒险模式完成次数'],
    ['模仿者选卡行数修改', '调整模仿者选卡界面的行数'],
    ['尝试取消异常报错闪退', '抑制部分脚本异常导致的游戏闪退'],
    ['投小鬼车 / 弹小鬼伞 / 寒冰大喷菇', '趣味玩法脚本'],
    ['菲米狠狠爆金币', '快速掉落大量金币'],
    ['[PGvZ] 系列', 'PGvZ 专属脚本:三档游戏速度、添加融合配方、伞动作修改、不显示植物卡槽名称等'],
    ['Dev_ 系列', '开发调试用脚本(如出怪汇流点验证、击杀统计),普通玩家无需使用'],
    ['example.py', '参数模板示例,想了解脚本参数怎么配置可以参考它'],
], [0.36, 0.64])
add_heading(story, '14.3 关于脚本分类', 1)
body(story, '脚本名以 [PGvZ] 开头的为 PGvZ 版本专用,在其他版本上可能无效;'
            '以 Dev_ 开头的为开发调试脚本,不影响正常使用;'
            '其余脚本在 PGvZ、PvZ.net 等版本上通用。分享自己编写的脚本时,'
            '把 .py 文件(以及可选的 .config.json 参数描述)放进快捷脚本文件夹即可被自动识别。')

# ══════ 第 15 章 花园页 ══════
add_heading(story, '第15章 花园页:花园管理', 0)
body(story, '花园功能目前仅 Windows 端提供,包含六个场景页:主花园1、主花园2、主花园(夜)、'
            '蘑菇园1、蘑菇园2、水族馆。'
            '进入对应页签后,可以按格子查看当前花园中的植物,选择植物进行放置或替换,'
            '快速打理花园、完成收集类目标。搭配杂项页的『自动浇水』开关(见第4章),'
            '连浇水都可以省了。')

# ══════ 第 16 章 状态管理与软件设置 ══════
add_heading(story, '第16章 状态管理与软件设置', 0)
add_heading(story, '16.1 状态管理', 1)
body(story, 'Windows 端点击底部『状态管理』(Android 端在抽屉"更多功能"组中打开『状态管理』),'
            '可以把所有页签的开关、输入框、下拉框状态整体保存与恢复:'
            '输入名称后点『保存当前』建立自己的配置方案;选中任意条目点『加载』一键恢复;'
            '『详细信息』展示该条目与默认状态的差异(标星项为开启的开关);『删除』移除不需要的条目。')
body(story, '列表中的『上次状态』由程序在退出时自动保存且不可删除。'
            '配合『环境』中的『自动应用上次配置』,下次启动自动恢复全部状态,'
            '并在连上游戏后自动重发已开启的开关,无需逐个再点一遍。')
add_heading(story, '16.2 环境设置', 1)
body(story, 'Windows 端点击底部『环境』打开,Android 端在抽屉中点『设置』,两端的设置项相同:')
make_table(story, ['设置项', '说明'], [
    ['允许自动连接', '连接失败后自动反复重试,直到连上游戏'],
    ['取消发送连接提醒', '连接成功后,游戏内不再弹出连接成功提示'],
    ['允许自动更新按钮状态', '切换页签时自动从游戏同步开关的真实状态'],
    ['启动时自动检查更新', '启动时检查新版本,仅提示不自动下载'],
    ['自动应用上次配置', '启动时自动恢复上次关闭前保存的状态'],
], [0.34, 0.66])
add_heading(story, '16.3 界面缩放与文件目录', 1)
body(story, '本节功能仅 Windows 端提供。底部『界面缩放』的 + / - 按钮以 100% 为基准调整界面大小,'
            '适配不同分辨率的屏幕。'
            '『打开文件目录』直接打开程序所在文件夹——阵型、快捷脚本、选项、出怪表都在'
            '『配置文件』子文件夹中,备份或分享配置只需复制对应文件。')

# ══════ 第 17 章 获取更新 ══════
add_heading(story, '第17章 获取更新', 0)
add_heading(story, '17.1 检查更新', 1)
body(story, '在『环境』(Android 端为『设置』)中勾选『启动时自动检查更新』后,'
            '每次启动会自动检查新版本(仅提示,不自动下载);'
            '也可以随时手动检查:Windows 端点击底部『获取更新』,Android 端打开抽屉中的『获取新版本』。'
            '更新窗口会显示当前版本号;发现新版本时,会一并列出新版本号、安装包大小与更新说明。')
add_heading(story, '17.2 Windows 端更新', 1)
body(story, '在更新窗口选择下载渠道(多个网盘与代码托管线路,会自动优先可用线路),'
            '点击『下载并更新』,底部进度条实时显示百分比、已下载大小与速度。'
            '下载完成后工具自动校验、替换并重启,全程无需手动操作。')
body(story, '若自动更新服务不可用,工具会提示前往发布页手动下载,'
            '按第2章的渠道重新安装即可,配置文件会保留。')
add_heading(story, '17.3 Android 端更新', 1)
body(story, '手机端发现新版本后会弹出对话框,显示当前版本、新版本说明与下载渠道'
            '(GitHub 海外线路、Gitee 国内线路),选择渠道下载 APK 后,'
            '按普通应用安装流程确认覆盖安装即可。')

# ── 结语 + 附录 ──
story.append(Spacer(1, 14))
body(story, '本手册覆盖了 PvZWSTools 的全部常用功能。工具更新频繁,新功能以程序内说明与群公告为准。'
            '祝游玩愉快,玩得开心!')
add_heading(story, '附录 交流与下载', 0)
body(story, 'PvZWSTools 为免费开源项目,由 AmourLing 开发维护。任何功能建议、问题反馈与脚本分享,'
            '都欢迎通过以下渠道联系:')
make_table(story, ['渠道', '地址'], [
    ['官方 QQ 群', '1034609947(群文件可下载最新版,可交流玩法与反馈问题)'],
    ['GitHub 仓库', link('https://github.com/AmourLing/PvZWSTools', 'github.com/AmourLing/PvZWSTools')],
    ['Gitee 仓库', link('https://gitee.com/AmourLing0412/PvZWSTools', 'gitee.com/AmourLing0412/PvZWSTools')],
    ['更新说明', '各版本的新增功能与修复内容,可查阅程序目录下的更新说明文档'],
], [0.24, 0.76])

# ══════ 构建 ══════
doc.multiBuild(story)
print('body pages OK ->', OUT_BODY)

# ══════ 封面(ReportLab 封面引擎) ══════
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, 'scripts'))
from cover_render import detect_fonts, render_cover  # noqa: E402

cover_content = {
    'kicker': '植物大战僵尸改版玩家工具 · USER MANUAL',
    'hero': 'PvZWSTools 使用手册',
    'summary': 'PvZWSTools 通过连接游戏内脚本服务,提供出怪控制、战场编辑、阵型管理、'
               '快捷脚本等功能,支持 Windows 与 Android 双平台。本手册面向普通玩家,'
               '逐一介绍各项功能的用途与操作方法。',
    'meta': '文档版本 v1.0 · 2026 年 9 月 · 官方交流群 1034609947',
    'footer': 'PVZWSTOOLS · USER MANUAL',
    'year': '2026',
    'word': 'MANUAL',
}
cover_palette = {
    'primary': '#2e8baa',
    'secondary': '#6fb3c9',
    'text': '#151513',
    'muted': '#7f7d75',
    'bg': '#ffffff',
}
render_cover('01', cover_content, OUT_COVER, palette=cover_palette, fonts=detect_fonts())
print('cover OK ->', OUT_COVER)

# ══════ 合并封面 + 正文 ══════
from pypdf import PdfReader, PdfWriter, Transformation  # noqa: E402

A4_W, A4_H = 595.28, 841.89


def normalize(page):
    w, h = float(page.mediabox.width), float(page.mediabox.height)
    if abs(w - A4_W) > 2 or abs(h - A4_H) > 2:
        page.add_transformation(Transformation().scale(sx=A4_W / w, sy=A4_H / h))
        page.mediabox.lower_left = (0, 0)
        page.mediabox.upper_right = (A4_W, A4_H)
    return page


writer = PdfWriter()
writer.add_page(normalize(PdfReader(OUT_COVER).pages[0]))
for pg in PdfReader(OUT_BODY).pages:
    writer.add_page(normalize(pg))
writer.add_metadata({
    '/Title': 'PvZWSTools 使用手册',
    '/Author': 'AmourLing',
    '/Creator': 'PvZWSTools',
    '/Subject': 'PvZWSTools 玩家使用手册:功能介绍与操作说明',
})
with open(OUT_FINAL, 'wb') as f:
    writer.write(f)
print('final OK ->', OUT_FINAL)
